/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/auth/login-attempts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List login attempts
         * @description ``GET /admin/login-attempts/``. Filterable by ``identifier``/``ip_address``/``user``/
         *     ``success``.
         */
        get: operations["admin_auth_login_attempts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List any user's sessions
         * @description ``GET /admin/sessions/``. Any user's rows, filterable by ``?user=``.
         */
        get: operations["admin_auth_sessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/sessions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke any user's session
         * @description ``DELETE /admin/sessions/{id}/``. Any user's session.
         */
        delete: operations["admin_auth_sessions_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/trusted-devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List any user's trusted devices
         * @description ``GET /admin/trusted-devices/``. Any user's rows, filterable by ``?user=`` —
         *     ``docs/CONTRACT.md`` §11 item 2 (the same gap item 18 flags for the self-service pair).
         */
        get: operations["admin_auth_trusted_devices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/trusted-devices/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke any user's trusted device
         * @description ``DELETE /admin/trusted-devices/{id}/``. Any user's trusted device.
         */
        delete: operations["admin_auth_trusted_devices_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/users/{id}/2fa/force-disable/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force-disable every 2FA method for a user
         * @description is_superuser-only, unconditionally — never satisfied by plain is_staff.
         */
        post: operations["admin_auth_users_2fa_force_disable_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/users/{id}/security/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user's 2FA status, active session count, and lock status
         * @description ``GET /admin/users/{id}/security/``. A read-only aggregate — no model of its own.
         */
        get: operations["admin_auth_users_security_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/users/{id}/unlock/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear a user's lockout, across every identifier they could have typed
         * @description ``POST /admin/users/{id}/unlock/``.
         */
        post: operations["admin_auth_users_unlock_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/disable/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable one enrolled 2FA method
         * @description Requires the caller's current password as a re-auth step.
         */
        post: operations["auth_2fa_disable_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/otp/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a two_factor-purpose OTP challenge for an eligible email_otp/phone_otp second factor
         * @description ``POST /2fa/otp/request/`` — not in ``docs/CONTRACT.md``'s frozen §5 table (see this
         *     module's own docstring). Gated by the pending token itself rather than an identifier: no
         *     decoy path applies, since the caller already proved a primary factor to obtain the pending
         *     token in the first place — unlike ``/otp/request/``, there is no unauthenticated-identifier
         *     enumeration surface here to protect.
         */
        post: operations["auth_2fa_otp_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/recovery-codes/regenerate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate the caller's recovery codes
         * @description Requires the caller's current password as a re-auth step. Returns the PLAINTEXT codes once — never retrievable again.
         */
        post: operations["auth_2fa_recovery_codes_regenerate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the caller's own 2FA enrollment and eligibility status
         * @description `enrolled_methods` is what the caller has actually set up; `eligible_methods` is that set filtered by the host's current TWO_FACTOR["ALLOWED_METHODS"].
         */
        get: operations["auth_2fa_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/totp/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a pending TOTP enrollment
         * @description ``POST /2fa/totp/confirm/``. Rejects a confirm attempt against an already-confirmed
         *     device, or with no pending enrollment at all, with the same ``400`` shape as a wrong code —
         *     every rejection here is a validation failure, never a distinguishable error.
         */
        post: operations["auth_2fa_totp_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/totp/enroll/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a TOTP enrollment
         * @description Returns a plaintext secret and an otpauth:// URI, once. A prior unconfirmed (or disabled) enrollment is silently replaced. Confirm with POST /2fa/totp/confirm/ before this method counts toward eligible_methods.
         */
        post: operations["auth_2fa_totp_enroll_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem a pending 2FA token with a second-factor code
         * @description Exactly one of `code`/`link_token` is required. `challenge_id` is required for email_otp/phone_otp (obtained from POST /2fa/otp/request/). The server re-derives eligible methods itself — a client-claimed `method` not in that fresh set is rejected even if the client presents an otherwise-valid code for it.
         */
        post: operations["auth_2fa_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/account/verify-contact/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a contact-verification OTP challenge
         * @description ``POST /account/verify-contact/confirm/``. An unresolved/expired/wrong-purpose challenge,
         *     and one verified by a different user than the caller, all produce the identical
         *     ``otp_challenge_invalid`` shape — same rule ``OtpVerifyView`` applies to its own challenges.
         */
        post: operations["auth_account_verify_contact_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/account/verify-contact/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an OTP challenge to verify the caller's own email or phone
         * @description ``POST /account/verify-contact/request/``. No decoy path — the caller is already
         *     authenticated, so the identifier being verified always resolves (to themselves).
         */
        post: operations["auth_account_verify_contact_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with an identifier and password
         * @description Authenticates with a password. Returns real tokens directly when no second factor is required, or a pending_2fa handshake (`pending_token`, `eligible_methods`) when it is. An unknown identifier and a known identifier with a wrong password return the identical 401 body — this endpoint never reveals whether an identifier exists.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out the caller's current session
         * @description ``POST /logout/``. Revokes the CALLER's own current session only — identified from the
         *     access token's own ``sid`` claim (``request.auth``, populated by ``JWTAuthentication``), never
         *     from a request body — and clears both auth cookies. This view is ``user_logged_out``'s sole
         *     emitter (``signals.py``).
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out every session for the caller
         * @description ``POST /logout/all/``. Revokes every session for the caller, including the one making this
         *     request.
         */
        post: operations["auth_logout_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/methods/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enabled authentication methods and the 2FA policy
         * @description Unauthenticated discovery endpoint — returns which login methods and 2FA policy this deployment has enabled. The same response for every caller; cached accordingly.
         */
        get: operations["auth_methods_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a login OTP challenge
         * @description Real or decoy, indistinguishably — this endpoint never reveals whether `identifier` resolves to a real account. 400 only when `channel`'s auth method isn't enabled.
         */
        post: operations["auth_otp_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/resend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend an OTP challenge's code
         * @description Reuses the same challenge_id/destination with a fresh code and expiry.
         */
        post: operations["auth_otp_resend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an OTP code or magic-link token and complete login
         * @description Exactly one of `code`/`link_token` is required. Returns the same shape as `/login/`. `created` is `true` only when this call just auto-provisioned a new account for an unrecognized identifier on an AUTO_PROVISION_METHODS-enabled method.
         */
        post: operations["auth_otp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the authenticated user's password
         * @description Requires the current password. Revokes every session for this user, including the one making this request — the client must log in again afterward.
         */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a password reset with an OTP code or magic-link token
         * @description Exactly one of `code`/`link_token` is required.
         */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset OTP challenge
         * @description Always returns 200, whether or not `identifier` resolves to a real account — this endpoint never reveals account existence.
         */
        post: operations["auth_password_reset_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's own sessions
         * @description ``GET /sessions/``. Lists the CALLER's own ``AuthSession`` rows only, filtered at the
         *     queryset level.
         */
        get: operations["auth_sessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of the caller's own sessions
         * @description ``DELETE /sessions/{id}/``. ``404``, never ``403``, for a session id that exists but isn't
         *     the caller's own — see this module's own docstring.
         */
        delete: operations["auth_sessions_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token for a fresh access token
         * @description Reads the refresh token from the cookie (default transport) or the request body (REFRESH_COOKIE['TRANSPORT'] == 'body'). Re-sets the cookie on success. A replayed (already-rotated) refresh token revokes the whole session and fires refresh_reuse_detected.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an access token without authenticating as it
         * @description Always 200. Returns {valid: true, claims} for a live, correctly-signed access token, or {valid: false} for anything else — expired, malformed, wrong typ, or tampered.
         */
        post: operations["auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/trusted-devices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's own trusted devices
         * @description ``GET /trusted-devices/``. Lists the CALLER's own ``TrustedDevice`` rows only.
         */
        get: operations["auth_trusted_devices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/trusted-devices/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of the caller's own trusted devices
         * @description ``DELETE /trusted-devices/{id}/``. Same ownership-check pattern as
         *     ``SessionRevokeView`` — ``404``, never ``403``, for a device id that isn't the caller's own.
         */
        delete: operations["auth_trusted_devices_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminUserSecurityResponse: {
            two_factor_status: components["schemas"]["TwoFactorStatusResponse"];
            active_session_count: number;
            lock_status: components["schemas"]["LockStatusResponse"];
        };
        AuthMethodsResponse: {
            allowed_auth_methods: string[];
            two_factor: components["schemas"]["TwoFactorMethods"];
        };
        /**
         * @description ``GET /sessions/``/``GET /admin/sessions/`` row shape — Phase 8. ``current_jti`` is never
         *     present here (this repo's ``CLAUDE.md`` rule 4: a refresh token's secret component).
         */
        AuthSession: {
            id: string;
            device_label: string;
            ip_address: string;
            user_agent: string;
            remember_me: boolean;
            rotation_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            revoked_at: string | null;
            revoked_reason: string | null;
        };
        /**
         * @description ``AdminUserSecurityResponseSerializer.lock_status`` — Phase 8, not specified by
         *     ``docs/CONTRACT.md`` §5 beyond the key's name. ``locked``/``until`` are ``null`` when
         *     ``LOCKOUT["LOCK_SCOPE"]`` is ``"identifier_and_ip"``/``"ip"``, where no single IP answers "is
         *     this USER locked?" — never a possibly-wrong ``false`` (this repo's ``CLAUDE.md`` rule 3: fail
         *     closed rather than silently assert a security state this app cannot actually verify).
         */
        LockStatusResponse: {
            scope: string;
            locked: boolean | null;
            /** Format: date-time */
            until: string | null;
        };
        /**
         * @description ``GET /admin/login-attempts/`` row shape — Phase 8. ``user`` is ``null`` for an
         *     ``identifier`` that never resolved to a real account (``models.LoginAttempt``'s own
         *     docstring) — the one model where that distinction is recorded at all.
         */
        LoginAttempt: {
            id: number;
            user: number | null;
            identifier: string;
            method: string;
            ip_address: string;
            user_agent: string;
            success: boolean;
            failure_reason: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description The 2FA-required branch of the shared login response. HTTP 200 — this is not an error
         *     response and is never wrapped in appkit's error envelope (``docs/CONTRACT.md`` §5).
         */
        LoginPendingTwoFactorResponse: {
            pending_token: string;
            eligible_methods: string[];
        };
        LoginRequestRequest: {
            identifier: string;
            password: string;
            /** @default false */
            remember_me: boolean;
        };
        LoginResponse: components["schemas"]["LoginTokensResponse"] | components["schemas"]["LoginPendingTwoFactorResponse"];
        /**
         * @description The no-2FA-required branch of the shared login response (``docs/CONTRACT.md`` §5's
         *     ``/login/``/``/otp/verify/`` rows). ``refresh`` is present only when
         *     ``REFRESH_COOKIE["TRANSPORT"] == "body"`` — omitted (never null) under the default
         *     ``"cookie"`` transport, where the refresh token travels as an HttpOnly cookie instead.
         */
        LoginTokensResponse: {
            access: string;
            refresh?: string;
            session_id: string;
            created: boolean;
        };
        LogoutAllResponse: {
            revoked_count: number;
        };
        LogoutAllResponseRequest: {
            revoked_count: number;
        };
        /**
         * @description * `email` - email
         *     * `phone` - phone
         * @enum {string}
         */
        OtpChannelEnum: "email" | "phone";
        OtpRequestRequest: {
            identifier: string;
            channel: components["schemas"]["OtpChannelEnum"];
        };
        OtpRequestResponse: {
            challenge_id: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            resend_available_at: string;
        };
        OtpResendRequest: {
            challenge_id: string;
        };
        OtpVerifyRequest: {
            challenge_id: string;
            code?: string;
            link_token?: string;
        };
        OtpVerifyResponse: components["schemas"]["LoginTokensResponse"] | components["schemas"]["LoginPendingTwoFactorResponse"];
        PaginatedAuthSessionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AuthSession"][];
        };
        PaginatedLoginAttemptList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["LoginAttempt"][];
        };
        PaginatedTrustedDeviceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TrustedDevice"][];
        };
        PasswordChangeRequest: {
            old_password: string;
            new_password: string;
        };
        PasswordResetConfirmRequest: {
            challenge_id: string;
            code?: string;
            link_token?: string;
            new_password: string;
        };
        PasswordResetRequestRequest: {
            identifier: string;
        };
        RecoveryCodesRegenerateRequest: {
            password: string;
        };
        /** @description The PLAINTEXT recovery codes — returned once, the same rule as the TOTP secret. */
        RecoveryCodesResponse: {
            codes: string[];
        };
        /**
         * @description ``POST /token/refresh/`` request body — Phase 8. ``refresh`` is used only under
         *     ``REFRESH_COOKIE["TRANSPORT"] == "body"``; under the default ``"cookie"`` transport the
         *     refresh token is read from the cookie instead (``login_flow.read_refresh_token``), never
         *     from this field, so it stays optional here regardless of transport.
         */
        TokenRefreshRequest: {
            refresh?: string;
        };
        /**
         * @description ``docs/CONTRACT.md`` §5's ``200 {access, session_id}`` — deliberately no ``created`` key,
         *     unlike ``LoginTokensResponseSerializer``: a refresh is never a fresh login.
         */
        TokenRefreshResponse: {
            access: string;
            refresh?: string;
            session_id: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        /**
         * @description ``valid: false`` responses omit ``claims`` entirely — there is nothing trustworthy to
         *     return once verification fails.
         */
        TokenVerifyResponse: {
            valid: boolean;
            claims?: {
                [key: string]: unknown;
            };
        };
        TotpConfirmRequest: {
            code: string;
        };
        /**
         * @description ``POST /2fa/totp/enroll/`` response. The ONE moment the plaintext secret is ever
         *     returned — never present in any other response this app produces.
         */
        TotpEnrollResponse: {
            secret: string;
            otpauth_uri: string;
        };
        /**
         * @description ``POST /2fa/totp/enroll/`` response. The ONE moment the plaintext secret is ever
         *     returned — never present in any other response this app produces.
         */
        TotpEnrollResponseRequest: {
            secret: string;
            otpauth_uri: string;
        };
        /**
         * @description ``GET /trusted-devices/``/``GET /admin/trusted-devices/`` row shape — Phase 8.
         *     ``token_hash`` is never present here (this repo's ``CLAUDE.md`` rule 4).
         */
        TrustedDevice: {
            id: number;
            device_label: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            revoked_at: string | null;
        };
        TwoFactorDisableRequest: {
            method: components["schemas"]["TwoFactorMethodEnum"];
            password: string;
        };
        /**
         * @description * `totp` - totp
         *     * `email_otp` - email_otp
         *     * `phone_otp` - phone_otp
         *     * `recovery_code` - recovery_code
         * @enum {string}
         */
        TwoFactorMethodEnum: "totp" | "email_otp" | "phone_otp" | "recovery_code";
        TwoFactorMethods: {
            policy: string;
            allowed_methods: string[];
        };
        /**
         * @description * `email_otp` - email_otp
         *     * `phone_otp` - phone_otp
         * @enum {string}
         */
        TwoFactorOtpRequestMethodEnum: "email_otp" | "phone_otp";
        /**
         * @description ``POST /2fa/otp/request/`` — not in ``docs/CONTRACT.md``'s frozen §5 table, a Phase 7
         *     addition recorded as a deviation in its §11 register: ``/2fa/verify/``'s frozen body has no
         *     ``challenge_id`` of its own, and ``/otp/request/`` is hardcoded to ``purpose="login"``, so
         *     ``email_otp``/``phone_otp`` as a SECOND factor needs its own request step, gated by the
         *     pending token itself rather than an identifier (this endpoint never takes one).
         */
        TwoFactorOtpRequestRequest: {
            pending_token: string;
            method: components["schemas"]["TwoFactorOtpRequestMethodEnum"];
        };
        /** @description ``GET /2fa/status/`` response — ``docs/CONTRACT.md`` §5. */
        TwoFactorStatusResponse: {
            policy: string;
            enrolled_methods: string[];
            eligible_methods: string[];
        };
        /**
         * @description ``POST /2fa/verify/`` — ``docs/CONTRACT.md`` §5. Every method here needs exactly one of
         *     ``code``/``link_token`` (``totp``/``recovery_code`` always via ``code``; ``email_otp``/
         *     ``phone_otp`` via either, same magic-link-lives-here rule ``OtpVerifySerializer`` uses), so
         *     the shared cross-field helper applies universally, not just to the OTP-based methods.
         *     ``challenge_id`` is an addition beyond the frozen body (same §11 deviation as
         *     ``TwoFactorOtpRequestSerializer`` above) — required only for ``"email_otp"``/``"phone_otp"``,
         *     a method-conditional rule checked at the view layer rather than here.
         */
        TwoFactorVerifyRequest: {
            pending_token: string;
            method: components["schemas"]["TwoFactorMethodEnum"];
            code?: string;
            link_token?: string;
            challenge_id?: string;
            /** @default false */
            trust_device: boolean;
        };
        VerifyContactConfirmRequest: {
            challenge_id: string;
            code: string;
        };
        VerifyContactRequestRequest: {
            field: components["schemas"]["OtpChannelEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_auth_login_attempts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLoginAttemptList"];
                };
            };
        };
    };
    admin_auth_sessions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuthSessionList"];
                };
            };
        };
    };
    admin_auth_sessions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such session. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_auth_trusted_devices_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTrustedDeviceList"];
                };
            };
        };
    };
    admin_auth_trusted_devices_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such trusted device. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_auth_users_2fa_force_disable_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_auth_users_security_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserSecurityResponse"];
                };
            };
        };
    };
    admin_auth_users_unlock_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_2fa_disable_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorDisableRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TwoFactorDisableRequest"];
                "multipart/form-data": components["schemas"]["TwoFactorDisableRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description method is not currently enrolled, or an incorrect password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_2fa_otp_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorOtpRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TwoFactorOtpRequestRequest"];
                "multipart/form-data": components["schemas"]["TwoFactorOtpRequestRequest"];
            };
        };
        responses: {
            /** @description challenge_id, expires_at, resend_available_at. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired pending token, or method not eligible. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_2fa_recovery_codes_regenerate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryCodesRegenerateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RecoveryCodesRegenerateRequest"];
                "multipart/form-data": components["schemas"]["RecoveryCodesRegenerateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesResponse"];
                };
            };
            /** @description Incorrect password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_2fa_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoFactorStatusResponse"];
                };
            };
        };
    };
    auth_2fa_totp_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TotpConfirmRequest"];
                "multipart/form-data": components["schemas"]["TotpConfirmRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No pending enrollment, already confirmed, or an invalid code. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_2fa_totp_enroll_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpEnrollResponseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TotpEnrollResponseRequest"];
                "multipart/form-data": components["schemas"]["TotpEnrollResponseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpEnrollResponse"];
                };
            };
        };
    };
    auth_2fa_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TwoFactorVerifyRequest"];
                "multipart/form-data": components["schemas"]["TwoFactorVerifyRequest"];
            };
        };
        responses: {
            /** @description {access, session_id, created}. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/consumed pending token, or method not eligible/verified. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_account_verify_contact_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyContactConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyContactConfirmRequest"];
                "multipart/form-data": components["schemas"]["VerifyContactConfirmRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid, expired, or wrong-purpose challenge. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_account_verify_contact_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyContactRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyContactRequestRequest"];
                "multipart/form-data": components["schemas"]["VerifyContactRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpRequestResponse"];
                };
            };
            /** @description field isn't configured on this host, or the caller has no current value for it. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequestRequest"];
                "multipart/form-data": components["schemas"]["LoginRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials, a locked account, or 2FA required with no eligible second factor. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutAllResponseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutAllResponseRequest"];
                "multipart/form-data": components["schemas"]["LogoutAllResponseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutAllResponse"];
                };
            };
        };
    };
    auth_methods_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMethodsResponse"];
                };
            };
        };
    };
    auth_otp_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpRequestRequest"];
                "multipart/form-data": components["schemas"]["OtpRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpRequestResponse"];
                };
            };
            /** @description channel's auth method is not in ALLOWED_AUTH_METHODS. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_otp_resend_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpResendRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpResendRequest"];
                "multipart/form-data": components["schemas"]["OtpResendRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpRequestResponse"];
                };
            };
            /** @description Invalid challenge, cooldown not elapsed, or MAX_RESENDS exhausted. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_otp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpVerifyRequest"];
                "multipart/form-data": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpVerifyResponse"];
                };
            };
            /** @description Invalid, expired, consumed, or wrong-purpose challenge. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 2FA required with no eligible second factor. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChangeRequest"];
                "multipart/form-data": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wrong old_password, or the new password failed a configured validator. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired challenge, or the new password failed a configured validator. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description Always returned, unconditionally. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_sessions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuthSessionList"];
                };
            };
        };
    };
    auth_sessions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such session, or it isn't the caller's own. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            /** @description Missing, invalid, expired, or reused refresh token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenVerifyResponse"];
                };
            };
        };
    };
    auth_trusted_devices_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTrustedDeviceList"];
                };
            };
        };
    };
    auth_trusted_devices_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such trusted device, or it isn't the caller's own. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
