# Generated by Django 6.0.8 on 2026-09-05 11:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("current_jti", models.CharField(max_length=64, unique=True)),
                ("rotation_count", models.PositiveIntegerField(default=0)),
                ("device_label", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("remember_me", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user_logout", "user_logout"),
                            ("admin_revoked", "admin_revoked"),
                            ("reuse_detected", "reuse_detected"),
                            ("password_changed", "password_changed"),
                            ("expired", "expired"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"], name="jwt_multiau_user_id_9871b4_idx"
                    ),
                    models.Index(fields=["expires_at"], name="jwt_multiau_expires_8b2024_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("identifier", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("password", "password"),
                            ("email_otp", "email_otp"),
                            ("phone_otp", "phone_otp"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("success", models.BooleanField()),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_such_identifier", "no_such_identifier"),
                            ("wrong_credential", "wrong_credential"),
                            ("locked", "locked"),
                            ("two_factor_unavailable", "two_factor_unavailable"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["identifier", "created_at"], name="jwt_multiau_identif_2c5e36_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"], name="jwt_multiau_ip_addr_368ccf_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="jwt_multiau_user_id_3bd6d8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                (
                    "challenge_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "email"), ("phone", "phone")], max_length=8
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "login"),
                            ("password_reset", "password_reset"),
                            ("verify_contact", "verify_contact"),
                            ("two_factor", "two_factor"),
                        ],
                        max_length=16,
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("code_hash", models.CharField(max_length=64)),
                ("link_token_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField()),
                ("resend_count", models.PositiveSmallIntegerField(default=0)),
                ("max_resends", models.PositiveSmallIntegerField()),
                ("last_sent_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "consumed_at"],
                        name="jwt_multiau_user_id_747595_idx",
                    ),
                    models.Index(fields=["expires_at"], name="jwt_multiau_expires_51a6f2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "used_at"], name="jwt_multiau_user_id_643416_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("device_label", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"], name="jwt_multiau_user_id_e073de_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("method", models.CharField(choices=[("totp", "totp")], max_length=16)),
                ("secret_encrypted", models.TextField()),
                ("last_used_step", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "method"), name="unique_user_method_2fa_device"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VerifiedContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[("email", "email"), ("phone", "phone")], max_length=8
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verified_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "field", "value"), name="unique_user_field_value_verified"
                    )
                ],
            },
        ),
    ]
