# Generated by Django 6.0.8 on 2026-09-07 23:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_multiauth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authsession",
            options={"verbose_name": "auth session", "verbose_name_plural": "auth sessions"},
        ),
        migrations.AlterModelOptions(
            name="loginattempt",
            options={"verbose_name": "login attempt", "verbose_name_plural": "login attempts"},
        ),
        migrations.AlterModelOptions(
            name="otpchallenge",
            options={"verbose_name": "OTP challenge", "verbose_name_plural": "OTP challenges"},
        ),
        migrations.AlterModelOptions(
            name="recoverycode",
            options={"verbose_name": "recovery code", "verbose_name_plural": "recovery codes"},
        ),
        migrations.AlterModelOptions(
            name="trusteddevice",
            options={"verbose_name": "trusted device", "verbose_name_plural": "trusted devices"},
        ),
        migrations.AlterModelOptions(
            name="twofactordevice",
            options={
                "verbose_name": "two-factor device",
                "verbose_name_plural": "two-factor devices",
            },
        ),
        migrations.AlterModelOptions(
            name="verifiedcontact",
            options={
                "verbose_name": "verified contact",
                "verbose_name_plural": "verified contacts",
            },
        ),
        migrations.AlterField(
            model_name="authsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="current_jti",
            field=models.CharField(
                help_text="The refresh token's current JWT ID; replaced on every rotation.",
                max_length=64,
                unique=True,
                verbose_name="current JTI",
            ),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="device_label",
            field=models.CharField(blank=True, max_length=255, verbose_name="device label"),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expires at"),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="session ID",
            ),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="IP address"),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="last_used_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="last used at"),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="remember_me",
            field=models.BooleanField(
                default=False,
                help_text="Whether this session was issued a long-lived refresh token.",
                verbose_name="remember me",
            ),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="revoked at"),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="revoked_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_logout", "User logout"),
                    ("admin_revoked", "Admin revoked"),
                    ("reuse_detected", "Reuse detected"),
                    ("password_changed", "Password changed"),
                    ("expired", "Expired"),
                ],
                max_length=32,
                null=True,
                verbose_name="revoked reason",
            ),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="rotation_count",
            field=models.PositiveIntegerField(default=0, verbose_name="rotation count"),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="authsession",
            name="user_agent",
            field=models.CharField(blank=True, max_length=512, verbose_name="user agent"),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_such_identifier", "No such identifier"),
                    ("wrong_credential", "Wrong credential"),
                    ("locked", "Locked"),
                    ("two_factor_unavailable", "Two-factor unavailable"),
                ],
                max_length=32,
                null=True,
                verbose_name="failure reason",
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="identifier",
            field=models.CharField(
                help_text="Stored in plaintext, deliberately, so an admin can search it.",
                max_length=255,
                verbose_name="identifier",
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="IP address"),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="method",
            field=models.CharField(
                choices=[
                    ("password", "Password"),
                    ("email_otp", "Email OTP"),
                    ("phone_otp", "Phone OTP"),
                ],
                max_length=16,
                verbose_name="method",
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="success",
            field=models.BooleanField(verbose_name="success"),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="login_attempts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="user_agent",
            field=models.CharField(blank=True, max_length=512, verbose_name="user agent"),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="attempts"),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="challenge_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="challenge ID",
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("phone", "Phone")],
                max_length=8,
                verbose_name="channel",
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="code_hash",
            field=models.CharField(max_length=64, verbose_name="code hash"),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="consumed at"),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="destination",
            field=models.CharField(
                help_text="The actual email address or phone number the code was sent to.",
                max_length=255,
                verbose_name="destination",
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expires at"),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="last_sent_at",
            field=models.DateTimeField(
                help_text="Updated on every resend; drives the resend cooldown.",
                verbose_name="last sent at",
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="link_token_hash",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="link token hash"
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(
                help_text="Snapshotted from configuration when the challenge was created.",
                verbose_name="max attempts",
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="max_resends",
            field=models.PositiveSmallIntegerField(
                help_text="Snapshotted from configuration when the challenge was created.",
                verbose_name="max resends",
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("password_reset", "Password reset"),
                    ("verify_contact", "Verify contact"),
                    ("two_factor", "Two-factor"),
                ],
                max_length=16,
                verbose_name="purpose",
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="resend_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="resend count"),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_challenges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="recoverycode",
            name="code_hash",
            field=models.CharField(max_length=64, verbose_name="code hash"),
        ),
        migrations.AlterField(
            model_name="recoverycode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="recoverycode",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="used at"),
        ),
        migrations.AlterField(
            model_name="recoverycode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recovery_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="device_label",
            field=models.CharField(blank=True, max_length=255, verbose_name="device label"),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expires at"),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="last_used_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="last used at"),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="revoked at"),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="token_hash",
            field=models.CharField(max_length=64, unique=True, verbose_name="token hash"),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trusted_devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="twofactordevice",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="confirmed at"),
        ),
        migrations.AlterField(
            model_name="twofactordevice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="twofactordevice",
            name="disabled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="disabled at"),
        ),
        migrations.AlterField(
            model_name="twofactordevice",
            name="last_used_step",
            field=models.BigIntegerField(
                default=0,
                help_text="TOTP replay guard — the last time-step value that was accepted.",
                verbose_name="last used step",
            ),
        ),
        migrations.AlterField(
            model_name="twofactordevice",
            name="method",
            field=models.CharField(
                choices=[("totp", "TOTP")], max_length=16, verbose_name="method"
            ),
        ),
        migrations.AlterField(
            model_name="twofactordevice",
            name="secret_encrypted",
            field=models.TextField(verbose_name="encrypted secret"),
        ),
        migrations.AlterField(
            model_name="twofactordevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="two_factor_devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="verifiedcontact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="verifiedcontact",
            name="field",
            field=models.CharField(
                choices=[("email", "Email"), ("phone", "Phone")], max_length=8, verbose_name="field"
            ),
        ),
        migrations.AlterField(
            model_name="verifiedcontact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verified_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="verifiedcontact",
            name="value",
            field=models.CharField(
                help_text="The exact contact value that was verified.",
                max_length=255,
                verbose_name="value",
            ),
        ),
        migrations.AlterField(
            model_name="verifiedcontact",
            name="verified_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="verified at"),
        ),
    ]
